parameters:
#    iosh_blog.example.class: Iosh\BlogBundle\Example

services:
#    iosh_blog.example:
#        class: %iosh_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
